particlesJS("particles",{ //ここに書くのがHTMLのidに対応するもの
	"particles":{
		"number":{
			"value":50,//紙吹雪の数
			"density":{
				"enable":false,
				"value_area":200
			}
		},
		"color": {
        "value": ["#EA5532", "#F6AD3C", "#FFF33F", "#00A95F", "#00ADA9", "#00AFEC","#4D4398", "#E85298"]//紙吹雪の色の種類
		},
		"shape":{
			"type":"polygon",//形状はPolygon,つまり多角形
			"stroke":{
				"width":0,
			},
			"polygon":{
				"nb_sides":4//多角形の角の数
			}
			},
			"opacity":{
				"value":1,
				"random":false,
				"anim":{
					"enable":true,
					"speed":20,
					"opacity_min":0,
					"sync":false
				}
			},
			"size":{
				"value":5,
				"random":true,//サイズをランダムにする
				"anim":{
					"enable":true,
					"speed":1,
					"size_min":1,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
			"speed":5,//小さくするとゆっくり、大きくすると速くなる
			"direction":"bottom",//落ちる向き
			"random":false,//動きをランダムにするか
			"straight":false,//まっすぐ落ちるかどうか
			"out_mode":"out",//画面の外に出るか
			"bounce":false,//跳ね返るかどうか
				"attract":{
					"enable":false,
					"rotateX":600,
					"rotateY":1200
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			},
		},
		"retina_detect":true
	});
    